app = "ussd2-0"
primary_region = "nbo" # Nairobi - you can change this to your preferred region

[env]
  PORT = "8080" # Next.js typically runs on port 3000, but Fly.io often uses 8080 by default

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1
