app = "ussd2-0"
primary_region = "jnb" # Johannesburg, South Africa

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1
